kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: demo-jenkins-cluster
nodes:
  - role: control-plane
    # add a mount from /path/to/my/files on the host to /files on the node
    extraMounts:
      - hostPath: /mnt/d/CODING/K8sMount/jenkins
        containerPath: /mnt/d/CODING/K8sMount/jenkins
