apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
spec:
  rules:
    - host: example.com # Replace with your domain name
      http:
        paths:
          - path: /order
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 3000
          - path: /product
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 3002
          - path: / # Default route to the frontend
            pathType: Prefix
            backend:
              service:
                name: store-front
                port:
                  number: 8080
